services:
  db:
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bills
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
  bill-app:
    container_name: bill-app
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      db:
          condition: service_healthy
networks:
  app-network:
    driver: bridge